### ISSUE TITLE
Open multiple shaq center on Redspher domain

### ISSUE THREAD

**Issue by Devauxni** [yoctu/shaq-view#50]
On redspher domain, our page can sometime be redirected to https://www.sharedquotation.com/ when we have several opened tab, even if it's on different code.
Exemple : 
https://shaq.redspher.com/center.html?usercode=35&theme=flash
https://shaq.redspher.com/center.html?usercode=66&theme=flash
https://shaq.redspher.com/center.html?usercode=67&theme=flash
https://shaq.redspher.com/center.html?usercode=106&theme=flash

Sometime it can happen after few minutes

**Comment by lvenier** [comment]
@Devauxni : I am not able to reproduce this issue. Do you still have it ?

**Comment by Devauxni** [comment]
nop seems ok. thank you
