### ISSUE TITLE
Map not working anymore on the shaq

### ISSUE THREAD

**Issue by Devauxni** [yoctu/shaq-view#67]
Hello,
The map is now working anymore on the shaq view.

We have this error message : 

Petit problème... Une erreur s'est produite
Google Maps ne s'est pas chargé correctement sur cette page. Pour plus d'informations techniques sur cette erreur, veuillez consulter la console JavaScript.

**Comment by lvenier** [comment]
@Devauxni : can you provide the url you are using ?

**Comment by Devauxni** [comment]
https://shaq.redspher.com/display.html?key=RI2008M0J3&type=&usercode=107&theme=flash

**Comment by lvenier** [comment]
@Devauxni I dont have any production account to make any test using connect.

Do you have a similiar issue with 83 ?
https://shaq.redspher.com/display.html?key=XXXXXXXX&type=&usercode=83&theme=flash

If yes can you send the js console log or provide me the credentials to connect ?

**Comment by lvenier** [comment]
added proper referrer to google maps authorization
